# $FreeBSD$

PROG=	stumbler
BINDIR=	/usr/local/sbin
LIBADD=	pcap ncursesw
CFLAGS=-g -Wno-missing-variable-declarations -Wno-incompatible-pointer-types-discards-qualifiers -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-sign-compare -Wno-cast-align
MAN=

.include <bsd.prog.mk>
