# $FreeBSD$

PROG=	stumbler

SRCS=	stumbler.c
INCS=	stumbler.h

BINDIR=	/usr/local/sbin
LIBADD=	pcap ncursesw
CFLAGS=-g -Wno-incompatible-pointer-types-discards-qualifiers
MAN=

.include <bsd.prog.mk>
